//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIMMonitoring.Service.FimWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FimWS.IFIMWebService")]
    public interface IFIMWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIMWebService/SendErrorPack", ReplyAction="http://tempuri.org/IFIMWebService/SendErrorPackResponse")]
        System.Collections.Generic.List<System.Guid> SendErrorPack(FIMMonitoring.Domain.ViewModels.WCF.ErrorPack errors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFIMWebService/SendErrorPack", ReplyAction="http://tempuri.org/IFIMWebService/SendErrorPackResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Guid>> SendErrorPackAsync(FIMMonitoring.Domain.ViewModels.WCF.ErrorPack errors);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFIMWebServiceChannel : FIMMonitoring.Service.FimWS.IFIMWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FIMWebServiceClient : System.ServiceModel.ClientBase<FIMMonitoring.Service.FimWS.IFIMWebService>, FIMMonitoring.Service.FimWS.IFIMWebService {
        
        public FIMWebServiceClient() {
        }
        
        public FIMWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FIMWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FIMWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FIMWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Guid> SendErrorPack(FIMMonitoring.Domain.ViewModels.WCF.ErrorPack errors) {
            return base.Channel.SendErrorPack(errors);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Guid>> SendErrorPackAsync(FIMMonitoring.Domain.ViewModels.WCF.ErrorPack errors) {
            return base.Channel.SendErrorPackAsync(errors);
        }
    }
}
