// <auto-generated />
namespace FIMMonitoring.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ImportErrorMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImportErrorMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201606240647234_ImportErrorMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
